### ISSUE TITLE
virtual_environments.md update from 3.5 to 3.6

### ISSUE THREAD

**Issue by kjcole** [chalmerlowe/intro_to_sprinting#101]
Typo (update) from Python 3.5 to 3.6.

**Comment by paulproteus** [comment]
Super rad. Any chance you can submit a pull request? I'd merge it today, if so.

**Comment by lorenz21** [comment]
@seawolf42 or @chalmerlowe this problem seems to be fixed in the 'overview'. [https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/virtual_environments.md](url)

**Comment by seawolf42** [comment]
@lorenz21 agreed, this is fixed. Closing the issue.
