### ISSUE TITLE
Need to resolve change to beowulf.txt

### ISSUE THREAD

**Issue by wescpy** [chalmerlowe/intro_to_sprinting#108]
After changing the upper 'B' to lower 'b', there are no instructions for the user to move fwd with this update after 'git diff.' Suggest that either you tell the user to "git checkout" to wipe the change, or ask them to review their commit skills from the previous lesson to submit it (then later revert back to the correct version with the upper 'B').

**Comment by seawolf42** [comment]
@wescpy good catch. Yes, the preferred next step would be to "roll back" the change with a `git checkout -- beowulf.txt`.

**Comment by chalmerlowe** [comment]
We need to confirm whether the instructions that led to this issue are still in the lesson plan somewhere and IF so, proceed with decision to correct OR leave as is, etc.

**Comment by wescpy** [comment]
It's not resolved yet. Please add the instructions above to this page: https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_common_operations.md

**Comment by seawolf42** [comment]
fixed by b81753c
