### ISSUE TITLE
git commit plus single quotes leads to errors on some Windows shells

### ISSUE THREAD

**Issue by paulproteus** [chalmerlowe/intro_to_sprinting#110]

**Comment by seawolf42** [comment]
@paulproteus good point. We should probably change all single quotes to double quotes throughout all the bash code blocks, *or* write something up about it early. @chalmerlowe do you have a preference? The former is more work but probably also alleviates more questions during the class.

**Comment by paulproteus** [comment]
I would vote for double-quotes, plus the contribution of a `STYLEGUIDE.md` which explains this chcoice, as well as as a travis-ci script that checks that we never violate this in the future.

If you do the first two, I'll volunteer to do to the travis-ci automation!

**Comment by chalmerlowe** [comment]
I am fine with double quotes in bash code blocks.
the styleguide.md idea is also quite good.

**Comment by seawolf42** [comment]
OK, it's now got the 'help wanted' tag... hopefully some brave soul will pick this up. 😄

**Comment by chalmerlowe** [comment]
@seawolf42 looks like this can be closed.

**Comment by seawolf42** [comment]
confirmed all of these have been previously addressed, closing
