### ISSUE TITLE
Documentation: github_submit_pull_request.md - inverted base and head fork

### ISSUE THREAD

**Issue by viktor-kryvyziuk** [chalmerlowe/intro_to_sprinting#112]
https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/github_submit_pull_request.md:
Confirm that the base fork is your fork
Confirm that the head fork is the original author's fork

Should be vice versa:
Confirm that the base fork is the original author's fork
Confirm that the head fork is your fork

P.S. Screenshot at the documentation page displays correct information.

**Comment by bsthorpe742** [comment]
This appears to be fixed with pull request #111.

**Comment by seawolf42** [comment]
Still incorrect:

<img width="993" alt="screen shot 2017-08-05 at 10 38 55" src="https://user-images.githubusercontent.com/2721922/28998696-59cf23ce-79cd-11e7-8276-327268e052a7.png">

**base** is the original author, **head** is my fork. However, the order of the items in the list is misleading. Changed with b4e0a7f
