### ISSUE TITLE
Add "Step X" to the instructions...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#122]
Before you work on this, let's discuss... Still considering whether this is the right method for doing this...

On this page, the sequence of Major Steps is hard to track because the first step has different instructions for multiple operating systems... and that blends oddly into the second step...

Considering edits to the headings to highlight them as major steps:

Download and Install git
Confirm your git install
Download and Install conda
Confirm your conda install

Should become:

Step One: Download and Install git
Step Two: Confirm your git install
Step Three: Download and Install conda
Step Four: Confirm your conda install

Also considering some alternate method to highlight the steps...

**Comment by Alestainer** [comment]
Hey! I'm gonna work on this one.
