### ISSUE TITLE
Consider adding Win/Linux/Mac icons to highlight steps specific to a given operating system

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#123]
Files like installing_tools.md

have steps that are Operating System (OS) specific.
Create a set of small icons that can be put next to each step to highlight the OS:

* Mac
* Linux
* Windows

Icons should be 'official' icons, should be sized to the same dimensions and labeled simply, i.e.:

mac_icon_48x48.png 

OR something similar.

Identify all steps with OS-specific need for icons AND either create issues to edit those pages OR fix all the pages to close this issue.

**Comment by Alestainer** [comment]
Hey! I'm on it.

**Comment by Alestainer** [comment]
https://commons.wikimedia.org/wiki/Category:Microsoft_Windows_logos#/media/File:Microsoft_Windows_logo_(Pre-XP).svg.jpg
https://commons.wikimedia.org/wiki/Category:Linux_logos#/media/File:Linux_logo.jpg
https://commons.wikimedia.org/wiki/Category:Apple_Inc._logos#/media/File:%D0%90pple_.png

These are the logos I found.

**Comment by seawolf42** [comment]
Awesome, I think those are great! 👍

**Comment by seawolf42** [comment]
Fixed with #134 .
