### ISSUE TITLE
Figure out why sometimes three remotes versus four remotes appear...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#125]
Depending on who runs the git remote command, sometimes three item show up, sometimes four. Research this, find out why and if necessary add some commentary to explain the phenomenon in the git_cloning.md file.

```
$ git remote -v
origin   https://github.com/myusername/intro_to_sprinting_codeless_project (fetch)
origin   https://github.com/myusername/intro_to_sprinting_codeless_project (push)
upstream https://github.com/chalmerlowe/intro_to_sprinting_codeless_project (fetch)
```

**Comment by seawolf42** [comment]
I need a repro. I *believe* this is an artifact of older versions of git and should not happen for anyone using any version of git newer than at least 5 years ago.

Updated the docs to reflect the "normal" output (with a push and fetch row for each remote) in #5bb744, closing the PR. Please reopen if we can reproduce.
