### ISSUE TITLE
Fix dead image link...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#128]
One of our images on this page: git_branch_merge.md is showing up as dead.
Figure out why and resolve.

The image shows up between these lines...

The history created by the above steps would look something like this:

**Source**: http://sentheon.com/images/27052016_branches.png

**Comment by Alestainer** [comment]
Hey! The link you left in the description gives 404

**Comment by chalmerlowe** [comment]
True, hence the need to figure out how to fix.

**Comment by chalmerlowe** [comment]
Fixed the link. Closed.
