### ISSUE TITLE
Missing resources on cloning a repository page

### ISSUE THREAD

**Issue by bobhilt** [chalmerlowe/intro_to_sprinting#140]
Page: https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_cloning.md
Resources section has empty brackets:

Resources:

- \[\]\(\)
- \[\]\(\)

**Comment by bobhilt** [comment]
I guess also true on other pages if no "resources."

**Comment by chalmerlowe** [comment]
@bobhilt there is an issue to provide appropriate resources on most of the pages. So ultimately, we will be filling in most of these as we go.
