### ISSUE TITLE
Add a new section related to merging conflicts

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#163]
Add a section related to merging files that have a merge conflict.

Some of the nuances behind this... we need to set up a scenario that will force a merge conflict.
We need some instructional material to walk uses through this scenario.
A framework for such an instructional walk through is present in the repo (git_merge_conflict.md) and is being worked by @chalmerlowe, but has not yet been added to the Table of Contents, so there are no links to it yet.

MERGE: Make a command executive decision on how we want to handle accepting PRs to the codeless repo (had conflicts when lots of people pushing to repository) (see above)
MERGE: Suggest that we have everyone do a successful push. Then we go into the upstream and make a single change and have the class make a conflicting chang... and then have everyone do a pull, resulting in a merge that must be resolved. **UPDATE: see comments below...** I am suggesting an alternate method of doing this...

**Comment by chalmerlowe** [comment]
@seawolf42 

I finished everything for the "What To Do" Section
[git_merge_conflict.md](https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_merge_conflicts.md)

Next, I need to duplicate all the steps and add explanatory content in the Big Picture section and the Deep Dive section, but plan on doing that once we confirm that the conflict merge steps in the What To Do section are legit/work, etc.

A major point of concern in how we deliver this content was the idea of having the instructor make a change to a file AND then have the students pull from upstream master and try to resolve a merge conflict.

Since we want the material to play a dual role (self-paced/instructed) I felt the simplest approach would be to have them just make a change to **their GitHub** repo and do a `git pull origin master` so they can experience a conflict ... noting of course, that just as we describe in the git merge lesson, that their normal course would be to do `git pull upstream master`

I felt like:

* between students wanting to race ahead
* students doing self-paced (at home OR at djangocon)
* for the sanity of the instructor (not having to remember to make the change and do all the things)

it would simply be faster/easier for go this route... but open for discussion.

**Comment by seawolf42** [comment]
@chalmerlowe fully agree with your approach, this does solve the self-paced scenario and also lets all users discover the same experience.

**Comment by chalmerlowe** [comment]
@seawolf42 

Added all the things. The draft of this section is done and the TOC and Nav have been autogenerated.

Closing this Issue based on commit #87fc666b
