### ISSUE TITLE
Need hyperlinks for windows and mac command line primer

### ISSUE THREAD

**Issue by JohnJohnsonIII** [chalmerlowe/intro_to_sprinting#164]
The resources section in https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_config.md needs the two hyperlinks omitted at the bottom.

**Comment by chalmerlowe** [comment]
@JohnJohnsonIII we may be able re-use the links found at the bottom of [prereq_student.md](prereq_student.md)
