### ISSUE TITLE
Clarity in Big Picture

### ISSUE THREAD

**Issue by JohnJohnsonIII** [chalmerlowe/intro_to_sprinting#168]
This is minor, but for clarity's sake, it might make sense in the Big Picture to use the example of the project we are to be working on(the codeless project) instead of the RPN Calculator. I think it will be helpful for newbies.  Again, nothing big and not needed for today's class. https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_cloning.md

**Comment by chalmerlowe** [comment]
The page referenced here has been corrected.

Closing.

**Comment by chalmerlowe** [comment]
Apparently, I can't read!

Re-opening.

**Comment by chalmerlowe** [comment]
closed by #0127b
