### ISSUE TITLE
Adding Multiple Files section move

### ISSUE THREAD

**Issue by JohnJohnsonIII** [chalmerlowe/intro_to_sprinting#170]
I think it would flow better if the Adding Multiple Files section was moved up to the Deep Dive section right under the example to add file. Putting it at the end feels a little disjointed, like you wrapped up the deep dive but then added another point.
https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/git_main_lifecycle.md

**Comment by chalmerlowe** [comment]
@JohnJohnsonIII i concur with this suggestion.
