### ISSUE TITLE
Broken link in prereq_instructor.md

### ISSUE THREAD

**Issue by wdouglashall** [chalmerlowe/intro_to_sprinting#179]
In prereq_instructor.md, the link for "Software Carpentry" article is broken:
https://swcarpentry.github.io/instructor-training/15-practices/

Instructor training is still there, but not sure of new URL for this article.

**Comment by joker2600** [comment]
@chalmerlowe @seawolf42 would this be the updated link?
https://carpentries.github.io/instructor-training/15-lesson-study/index.html

**Comment by chalmerlowe** [comment]
@joker2600 thanks for hunting this down...

I took a look.

I think this link is the right one:

https://carpentries.github.io/instructor-training/14-live/index.html

**Comment by wdouglashall** [comment]
Thanks! Fixed link in pull request.
