### ISSUE TITLE
"miniconda quickstart guide" link is broken

### ISSUE THREAD

**Issue by DanielGoldfarb** [chalmerlowe/intro_to_sprinting#192]
On page https://github.com/chalmerlowe/intro_to_sprinting/blob/master/class_materials/setup_data_science.md
the link who's link text is ""miniconda quickstart guide" is broken.  It goes to: https://conda.io/en/latest/install/quick.html but that page says "        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

**Comment by seawolf42** [comment]
thanks, fixing now

**Comment by seawolf42** [comment]
fixed in c28f055565574824939d872ca2a6f6b20b1de81b
