### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ndanielsen** [chalmerlowe/intro_to_sprinting#193]
Love the stuff in here.

What is it licensed under?

**Comment by jerivas** [comment]
I recall @seawolf42 mentioning it was public domain today at DjangoCon

**Comment by seawolf42** [comment]
That's a great question. It is freely available to use both as a reference and also as a guide or foundation of teaching it on your own in any context. "Public domain" was probably the wrong phrase for it (for instance you can't copy it, call it your own, and then sell tickets to your workshops and make massive profits), but it is designed to be freely available and reusable for the right reasons, like as an opening to sprinting at a conference or at a workshop put on by a club or group so everyone can learn.

@chalmerlowe do you have a more refined answer than that?

**Comment by seawolf42** [comment]
I'm agreeable to almost anything.

**Comment by chalmerlowe** [comment]
This has been open too long.
I decided on a fairly open/permissive Apache License and added it to the repo today.
