### ISSUE TITLE
add resources pertaining to miniconda

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#2]
Add to the virtual environment page some details in the resources section:
i.e. links to pages with more details on conda, virtual environments in conda, etc

**Comment by joefriedrich** [comment]
I added cheatsheets for Git, Conda, and VIM in pull request number 42. :alien:
They are in the Images folder.
Let me know if I should clean everything else out and only submit a pull request for those files.

**Comment by briansmithbeta** [comment]
@joefriedrich Has there been any movement on this issue?

**Comment by joefriedrich** [comment]
@briansmithbeta There has not been movement on the issue at this time.  Pull request 42 is still open as are 7 other requests.

**Comment by chalmerlowe** [comment]
Resources (cheatsheet, etc) were linked in the documentation. Closing.
