### ISSUE TITLE
correct spelling/grammar error: "we image"

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#200]
on the page `setup_data_science.md`, change the following text:

"we image" to "we imagine"
"python" to "Python"

**Comment by chalmerlowe** [comment]
@Santhoshmani1 Thanks for reaching out. I assigned this to you. Holler if you need some help.
If something comes up and you can't finish up, let me know and I will release it to the general public.

**Comment by Santhoshmani1** [comment]
Thanks @chalmerlowe for assigning the issue. 
I will fix the issue and will send a pr.

**Comment by Santhoshmani1** [comment]
@chalmerlowe I have fixed the issue and sent a pr . 
Please check it out. 
Thanks for letting me to work on this issue.
