### ISSUE TITLE
Add some steps in the virtual environment hands-on section

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#3]
Add some steps for users to follow to get their virtual env set up.

**Comment by chalmerlowe** [comment]
This was a bit vague, but I am anxious to help.
Can you clarify what you would like to see.

**Comment by jfmario** [comment]
Yes, I would like some clarification too

**Comment by joefriedrich** [comment]
Last I checked, we are using Conda as the virtual env.
After we get it setup, we could run them through Conda's intro:
http://conda.pydata.org/docs/test-drive.html
