### ISSUE TITLE
Developing Roadmaps for Python Programmers

### ISSUE THREAD

**Issue by sockduct** [chalmerlowe/intro_to_sprinting#30]
There are already some good roadmaps for aspiring Python developers including:
- [Google's Technical Development Guide](https://www.google.com/about/careers/students/guide-to-technical-development.html)
- [The Open-Source Computer Science Degree](https://github.com/mvillaloboz/open-source-cs-degree)
- [The Open Source Data Science Masters - Curriculum for Data Science](http://datasciencemasters.org/)

I would like to develop a roadmap for the "DevOps" track and am looking for input.  Any ideas/suggestions welcome to james<dot>r<dot>small<at>outlook<dot>com.

**Comment by chalmerlowe** [comment]
Thanks for including these.
At this moment, I want to leave these here for future reference, but don't want the Issue open, so closing.
