### ISSUE TITLE
Problems with "random thoughts..."

### ISSUE THREAD

**Issue by sockduct** [chalmerlowe/intro_to_sprinting#31]
In Windows 7 under PowerShell, git doesn't appear to like this filename as shown below.  What do you think about renaming this to "random_thoughts..." to see if that fixes it?

C:\...\sprintintro\intro_to_sprinting>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    random thoughts...

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        random thoughts

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by DLance96** [comment]
:+1:

**Comment by chalmerlowe** [comment]
I revised the file name. 
all should be right with the world now.
