### ISSUE TITLE
Set hyperlinked text to open in a new window

### ISSUE THREAD

**Issue by CrimsonPresident** [chalmerlowe/intro_to_sprinting#43]
Please make sure all hyperlinked items open a new window.

**Comment by james-prior** [comment]
Who is driving?

Let the person who is browsing, drive.
In other words, let the person who is browsing be in control.
Let the person who is browsing decide whether to open a link in a new window, a new tab, or within the current window/tab.

**Comment by chalmerlowe** [comment]
I did a bit of research on this. In rethinking this, my sense is that setting hyperlinks to open in a new window will go contrary to accepted principles of User Interface design. For more details, this [article](https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/) hosts some good discussion.
