### ISSUE TITLE
Tweak the instructions to follow the github >> git >> github workflow...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#47]
Right now, the **github overview** covers two factors of the github workflow:
* forks
* pull requests

The **git overview** then covers the git workflow of:
* cloning
* pushing

I suggest that we break the github workflow into two parts and bookend the git overview, so that the attendees get a smoother view of how a real workflow works:
### github overview, part 1
  * forks
### git
  * cloning
  * pushing
### github overview, part 2
  * pull requests

**Comment by seawolf42** [comment]
Split across pages. I think both pages need more content, but the split is done. Not sure when I'll have a chance to elaborate on either.

**Comment by chalmerlowe** [comment]
@seawolf42 
thanks.
good job.
closing.
