### ISSUE TITLE
create an overview on git

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#5]
add some short commentary to parallel the sections in the virtual environment page about git:
include section headers and highlevel overview, etc.

**Comment by DLance96** [comment]
Covered by #26 and expanded upon in #36 is there any major git concepts you think should be included?

EG: rebase, fetch (teaching people how to update a fork), branches?, checkout?

**Comment by seawolf42** [comment]
@chalmerlowe, you had an analogy with git as warehouses, trucks, pallets, etc, and there was a video for that... can you send me the link for that video?

**Comment by chalmerlowe** [comment]
@seawolf42 I will provide the link to the video.

**Comment by chalmerlowe** [comment]
The link in question is:
Jessica Kerr's (jessitron) talk "git happens"
https://youtu.be/yCh6TSLIQBQ

**Comment by chalmerlowe** [comment]
A git overview has been added over multiple commits.
The noted link to Jessitron's video has been added in commit c86d0b9.
Closing!
