### ISSUE TITLE
Merge Calculator AND Lesson Content

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#50]
Merge the Calculator and Lesson Content into a single repo.
This should:

- reduce some confusion
- eliminate some of the talk track
- speed things up so we can get to the hands-on sooner

**Comment by seawolf42** [comment]
As per our discussion, this should truly be a separate project. Additionally, students should not clone the intro-to-sprinting project but will instead first work on a dummy project (jokes list or similar) and then work on the rpncalc project. Additional instructions have been added to rpncalc project for instructors, and lesson 1 setup instructions have been shortened to reference the other project.
