### ISSUE TITLE
Add a code-less pull request 

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#51]
Add, if it is not already there, a place where the students submit a pull request that does not have anything to do with code.

The benefit of this is that they get to submit a pull request earlier in the day and can do so without having to wrap their head around any code, etc.

**Comment by chalmerlowe** [comment]
Create a simple project that will enable students to create fast and dirty pull requests

* without having to figure out the code, the nuances, etc.
* have it as a standalone project from this one
* add links to the standalone project in the course material

IDEAS:

* joke list
* famous works

**Comment by chalmerlowe** [comment]
I suggest having a file in the **code-less sample project** with the text from walrus and the carpenter, by lewis carroll:

http://www.jabberwocky.com/carroll/walrus.html

**Comment by 808kimosan** [comment]
Hey Chalmer, did you know that Beowulf is the oldest surviving Anglo-Saxon poem?  (It was also made into a very cool 3D animated film!)

**Comment by chalmerlowe** [comment]
Other suggestions include:
The Raven, edgar allen poe:
http://www.bartleby.com/102/84.html

Annabell-lee, edgar allen poe:
https://www.poets.org/poetsorg/poem/annabel-lee

The Road Not taken:
Robert Frost
https://www.poetryfoundation.org/resources/learning/core-poems/detail/44272

Do not go gently into that good night
Dylan Thomas:
https://www.poets.org/poetsorg/poem/do-not-go-gentle-good-night

jabberwocky:
lewis carroll
http://www.jabberwocky.com/carroll/jabber/jabberwocky.html

Flanders fields
John McRae
http://www.greatwar.co.uk/poems/john-mccrae-in-flanders-fields.htm

**Comment by lorenz21** [comment]
Short stories:
Hansel and Gretel:

**Comment by chalmerlowe** [comment]
** I created a new project on github with content for this **

https://github.com/chalmerlowe/intro_to_sprinting_codeless_project

I added a file to start it off...
The Walrus and the Carpenter

**Comment by seawolf42** [comment]
references to the codeless project have been added, removing myself from the assigned list.

**Comment by chalmerlowe** [comment]
Thanks, guys!
