### ISSUE TITLE
Add git diff AND git status commands to the lesson

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#53]
Add examples of using git diff to the lesson.
Also, add if not already present, some examples of using git status to see the changes to the repo

UPDATE:
provide multiple instances in the material where `git status` can help the attendees begin to better understand the status of their repo.
* before the make any changes
* after they make changes to a file
* after they add a file to the repo
* after they commit a file to the repo
* etc

Also identify places where `git diff` can be beneficial i.e. when attempting to understand how your material conflicts with a change to the upstream repo material.

**Comment by seawolf42** [comment]
git status added to lesson 5. Working on git diff now.

**Comment by seawolf42** [comment]
BTW @chalmerlowe, in Markdown it's helpful to put a blank line between differing structure types. In particular, not having a line break will cause problems with lists. Note the difference between:

Here's a list:
* item 1
* item 2

and:

Here's a list:

* item 1
* item 2

I've also gotten in the habit of adding a blank line after headings and other elements of note, just to remove ambiguity.

**Comment by seawolf42** [comment]
diff description added.
