### ISSUE TITLE
provide a list of example functions for students to tackle

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#54]
provide a summary list of example functions for students to possibly work on
having a ready made list of example functions available when we kick off the last big hands-on section will shorten the talk track and give students something to jump into right away.

**Comment by seawolf42** [comment]
@samsammurphy is working on this.

**Comment by chalmerlowe** [comment]
@samsammurphy took care of this. The content got merged. Closing!
