### ISSUE TITLE
Add to prerequisites

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#55]
Add a link to a basic "command line tools" tutorial or two (*nix and Windows) for the prerequisites section of the README.md
cd
mkdir
ls / dir
etc

**Comment by lorenz21** [comment]
**Basic command line tools**
Codecademy:
https://www.codecademy.com/learn/learn-the-command-line

itsfoss:
https://itsfoss.com/linux-commands-cheat-sheets/

**Comment by lorenz21** [comment]
@chalmerlowe Should this be just a link to the existing 'command-line tools' text? Or should this page also have a '**Resources**' section on the bottom of the page?

**Comment by chalmerlowe** [comment]
@lorenz21 I don't believe we need a resources section at the bottom of the Readme.md.
Since we claim that some command line is useful, i would suggest:

a link to a windows cheatsheet
a link to a bash cheatsheet (which covers linux/mac)

and
maybe a link to something deeper, a la your link to code academy.

**Comment by seawolf42** [comment]
There are already links in the git page, maybe consolidate and/or reference them fronreadme?

jeff

**Comment by chalmerlowe** [comment]
Just looked at the links on the git page.
I would suggest that we 
0) host the links on the README as prereqs.
1) reference the prereqs in the git lesson.

**Comment by chalmerlowe** [comment]
OK: so I added a link in the README.md Prequisites section to take students to the Student Preparation file, which has links to cmd/terminal lessons.

Closing this issue.
