### ISSUE TITLE
Add concrete steps for a basic work flow using git

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#6]
Add concrete examples of steps to take using git - the point is less about full explanations of each step and more about giving someone a quick and dirty look at the totality of the process.
things like:
config your git
add upstream
create branch
checkout branch
pull changes to master
add files
commit changes
merge branch
push to github
issue pull request

**Comment by horshacktest** [comment]
Github's help has great examples to most if not all of these tasks. They are clean and well written.  They are broken down into individual pages so maybe we can do this as a list of links.

Pointing people to Github help might inspire them to read more of it.

**Comment by seawolf42** [comment]
I really like that idea. I think a couple basic flows should be laid out and several other common tasks should be referenced by link to GH documentation.

**Comment by seawolf42** [comment]
I've updated lesson 5 with quite a few clarifications and some restructuring. Let me know if you think it needs more work @chalmerlowe, otherwise please close.
