### ISSUE TITLE
Replace image with revised version...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#60]
Replace the image in lesson_04:
`images/fork-repo-link.png`
with a similar image that shows a link pointing to the codeless project at:
https://github.com/chalmerlowe/intro_to_sprinting_codeless_project

**Comment by morrme** [comment]
Should it have the same name so that it just replaces the original?

**Comment by seawolf42** [comment]
yup, that is an ideal solution

**Comment by sigsevneo** [comment]
Hi @chalmerlowe , can you check https://github.com/chalmerlowe/intro_to_sprinting/pull/72. I think it covers what you require in this?

**Comment by morrme** [comment]
lol i was working on this but i couldnt match the rounded "circle"....i see the person who poached this 😒 just used an alternative......

**Comment by chalmerlowe** [comment]
@morrme thanks for looking into this.
@sigsevneo I will likely take the image and drop it into the overhaul branch of the code. We are gonna be ditching the current `master` branch in preference for the `overhaul` branch >>> which we will likely rename `master`.

This image appears to work. 

Thanks. Will close this out, as soon as I get the image merged in appropriately on the right branch.

**Comment by morrme** [comment]
@chalmerlowe sorry i didnt know you had one of your people on it. i didn't know if an alternate highlight would be acceptable.

**Comment by chalmerlowe** [comment]
@morrme I did not have this assigned to anyone @sigsevneo jumped on it and came up with something that is do-able.

this is generally how open source plays out. there are cases where more than one person attempts to tackle the same problem. and sometimes first wins. sometimes best wins. sometimes good enough wins.

= )

**Comment by chalmerlowe** [comment]
Closing, the image has been incorporated.
