### ISSUE TITLE
Change the list of functions into a table format

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#62]
In the Intro to the project (lesson 7, although that number may change)...

There is a long list of functions that could be added to the calculator.

Please convert this list to a table format.

Thanks.

**Comment by seawolf42** [comment]
That's a good idea. @samsammurphy do you want to take that or will you be able before the weekend? If not, I'll fix it.

**Comment by seawolf42** [comment]
The best structure would probably be:

| Code | Name | Description |
|:--:|:--|:--|
| - | Subtract | `x - y` |
| * | Multiply | `x * y` |

... and so on.

**Comment by samsammurphy** [comment]
sure will do..

**Comment by samsammurphy** [comment]
@chalmerlowe @seawolf42 

Done

**Comment by chalmerlowe** [comment]
Sweet. Thanks!
