### ISSUE TITLE
create menu framework

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#7]
create a bare-bones menu framework that future students will use.

**Comment by briansmithbeta** [comment]
"Menu Framework" seems a bit open-ended. Is this just a regular menu for certain commands or is "framework" intended to indicate some kind of generalized extensible way of adding menu items? What is the purpose of this menu and what will it be used for?

**Comment by briansmithbeta** [comment]
@chalmerlowe Can you please provide a more detailed deliverable description?

**Comment by joefriedrich** [comment]
I was thinking it was more like a syllabus with direct links to the documents in question.

**Comment by chalmerlowe** [comment]
The direction of the student's practice project has changed.
This issue will be closed.
