### ISSUE TITLE
Confirm bottom navigation on every page (prev, up, next)

### ISSUE THREAD

**Issue by seawolf42** [chalmerlowe/intro_to_sprinting#70]
Confirm that the bottom navigation on every page really does go to the right place. 

## Sections

* Up should go to table of contents
* Prev should go to last lesson of previous section
* Next should go to first lesson of this section

## Lessons

* Up should go to section page
* Prev should go to previous lesson (or section page if first lesson in section)
* Next should go to next lesson (or next section page if last lesson in section)

**Comment by 808kimosan** [comment]
Kimo will work on editing bottom navigation from the end (par 5) backwards, so someone else can work on navigation from the beginning if desired

**Comment by jpbatz** [comment]
I will start at the beginning, then.

**Comment by jpbatz** [comment]
Actually, appears to be done.

**Comment by chalmerlowe** [comment]
Jeff put stuff in...
the question is: was it done right.
Does each link point to the right place.

**Comment by jpbatz** [comment]
Yes - I tested each one on every page.

**Comment by chalmerlowe** [comment]
@jmacnut thanks. @808kimosan found a discrepancy on one of the later pages and is creating a patch to fix it.

Will close this issue as soon as that patch is issued.

He also seems to have found a page with NO navigation on the bottom at all. He will issue a patch for that.

**Comment by jpbatz** [comment]
Apologies, I may have fixed them already.  Will move on to another issue.

**Comment by 808kimosan** [comment]
@chalmerlowe Completed validation of all navigation buttons -- all good!

**Comment by chalmerlowe** [comment]
I am gonna close this. 
Thanks @jpbatz @808kimosan
