### ISSUE TITLE
Add some explanatory details on the git setup...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/intro_to_sprinting#74]
On the **overhaul** branch, [this page]( https://github.com/chalmerlowe/intro_to_sprinting/blob/overhaul/class_materials/git_config.md) talks about setting up git.
Add some verbiage to describe the fact that the git config, in this case is a global config for all git projects on your machine as opposed to a git config for this project.

**Comment by jpbatz** [comment]
Added some verbiage for this request.

**Comment by chalmerlowe** [comment]
@jpbatz thanks. closing this
ALSO: you should consider adding yourself to the authors.md file.
