### ISSUE TITLE
Consolidate links to dependencies (mini conda, git) in one place for easy parallel downloading.

### ISSUE THREAD

**Issue by briansmithbeta** [chalmerlowe/intro_to_sprinting#9]

**Comment by chalmerlowe** [comment]
Great comment...
we are adding a new install doc and are considering a suitable path forward for this.

**Comment by chalmerlowe** [comment]
@horshacktest this issue falls right in line with your task...

**Comment by horshacktest** [comment]
PR #40 may address this. If not I'll keep at it.

**Comment by briansmithbeta** [comment]
@horshacktest Yes, that looks good. I'll close the issue.
